name: Quality Assurance

on:
  push:
    branches: ["main", "initial"]
    tags-ignore: ["**"]
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Build
        run: go build -o docker-api-auth .

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Test
        run: go test ./...

  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0
