name: Release binaries

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64,arm64]
      fail-fast: false
    steps:
      - name: Git checkout
        uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Install xcaddy
        run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

      - name: Build xcaddy with plugin
        run: xcaddy build --with github.com/cego/caddy-docker-api-auth@latest=./ --output caddy-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: caddy-${{ matrix.goos }}-${{ matrix.goarch }}
